version: "3.7"

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        LANGUAGE: en 
    ports:
      - 8000:8000
    volumes:
      - ./:/app
