site_name: Docker 101
site_description: A tutorial for learning to use Docker
site_author: Docker
# site_url: https://squidfunk.github.io/mkdocs-material/

# Repository
repo_name: dockersamples/101-tutorial
repo_url: https://github.com/dockersamples/101-tutorial
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 Docker'

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: 'images/docker-labs-logo.svg'

extra_css:
  - css/styles.css
  - css/dark-mode.css

extra_javascript:
  - https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js
  - js/jquery.raptorize.1.0.js
  - js/custom.js

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/dockersamples/101-tutorial

# Extensions
markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dockersamples
      repo: 101-tutorial
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Page tree
nav:
  - Tutorial: 
    - Getting Started: tutorial/index.md
    - Our Application: tutorial/our-application/index.md
    - Updating our App: tutorial/updating-our-app/index.md
    - Sharing our App: tutorial/sharing-our-app/index.md
    - Persisting our DB: tutorial/persisting-our-data/index.md
    - Using Bind Mounts: tutorial/using-bind-mounts/index.md
    - Multi-Container Apps: tutorial/multi-container-apps/index.md
    - Using Docker Compose: tutorial/using-docker-compose/index.md
    - Image Building Best Practices: tutorial/image-building-best-practices/index.md
    - What Next?: tutorial/what-next/index.md
  - PWD Tips: pwd-tips/index.md
